// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package general;

/**
 * Provides type-specific helper functions.
 **/
public final class AppPrxHelper extends Ice.ObjectPrxHelperBase implements AppPrx
{
    private static final String __receive_name = "receive";

    public void receive(Message msg)
    {
        receive(msg, null, false);
    }

    public void receive(Message msg, java.util.Map<String, String> __ctx)
    {
        receive(msg, __ctx, true);
    }

    private void receive(Message msg, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_receive(begin_receive(msg, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_receive(Message msg)
    {
        return begin_receive(msg, null, false, false, null);
    }

    public Ice.AsyncResult begin_receive(Message msg, java.util.Map<String, String> __ctx)
    {
        return begin_receive(msg, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_receive(Message msg, Ice.Callback __cb)
    {
        return begin_receive(msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_receive(Message msg, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_receive(msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_receive(Message msg, Callback_App_receive __cb)
    {
        return begin_receive(msg, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_receive(Message msg, java.util.Map<String, String> __ctx, Callback_App_receive __cb)
    {
        return begin_receive(msg, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_receive(Message msg, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_receive(msg, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_receive(Message msg, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_receive(msg, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_receive(Message msg, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_receive(msg, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_receive(Message msg, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_receive(msg, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_receive(Message msg, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_receive(msg, 
                             __ctx, 
                             __explicitCtx, 
                             __synchronous, 
                             new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_receive(Message msg, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__receive_name, __cb);
        try
        {
            __result.prepare(__receive_name, Ice.OperationMode.Idempotent, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            Message.__write(__os, msg);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_receive(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __receive_name);
    }

    private static final String __receiveList_name = "receiveList";

    public void receiveList(Message[] msgs)
    {
        receiveList(msgs, null, false);
    }

    public void receiveList(Message[] msgs, java.util.Map<String, String> __ctx)
    {
        receiveList(msgs, __ctx, true);
    }

    private void receiveList(Message[] msgs, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_receiveList(begin_receiveList(msgs, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_receiveList(Message[] msgs)
    {
        return begin_receiveList(msgs, null, false, false, null);
    }

    public Ice.AsyncResult begin_receiveList(Message[] msgs, java.util.Map<String, String> __ctx)
    {
        return begin_receiveList(msgs, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_receiveList(Message[] msgs, Ice.Callback __cb)
    {
        return begin_receiveList(msgs, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_receiveList(Message[] msgs, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_receiveList(msgs, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_receiveList(Message[] msgs, Callback_App_receiveList __cb)
    {
        return begin_receiveList(msgs, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_receiveList(Message[] msgs, java.util.Map<String, String> __ctx, Callback_App_receiveList __cb)
    {
        return begin_receiveList(msgs, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_receiveList(Message[] msgs, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_receiveList(msgs, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_receiveList(Message[] msgs, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_receiveList(msgs, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_receiveList(Message[] msgs, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_receiveList(msgs, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_receiveList(Message[] msgs, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_receiveList(msgs, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_receiveList(Message[] msgs, 
                                              java.util.Map<String, String> __ctx, 
                                              boolean __explicitCtx, 
                                              boolean __synchronous, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_receiveList(msgs, 
                                 __ctx, 
                                 __explicitCtx, 
                                 __synchronous, 
                                 new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_receiveList(Message[] msgs, 
                                              java.util.Map<String, String> __ctx, 
                                              boolean __explicitCtx, 
                                              boolean __synchronous, 
                                              IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__receiveList_name, __cb);
        try
        {
            __result.prepare(__receiveList_name, Ice.OperationMode.Idempotent, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            MsgSeqHelper.write(__os, msgs);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_receiveList(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __receiveList_name);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static AppPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), AppPrx.class, AppPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static AppPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), AppPrx.class, AppPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static AppPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), AppPrx.class, AppPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static AppPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), AppPrx.class, AppPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static AppPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, AppPrx.class, AppPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static AppPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, AppPrx.class, AppPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Demo::App",
        "::Ice::Object"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[0];
    }

    public static void __write(IceInternal.BasicStream __os, AppPrx v)
    {
        __os.writeProxy(v);
    }

    public static AppPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            AppPrxHelper result = new AppPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
