// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package general;

public final class TomPrxHolder
{
    public
    TomPrxHolder()
    {
    }

    public
    TomPrxHolder(TomPrx value)
    {
        this.value = value;
    }

    public TomPrx value;
}
