spring:
  database:
    driverClassName: com.mysql.jdbc.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/appserver?characterEncoding=utf8&amp;autoReconnect=true&amp;failOverReadOnly=false&amp;allowMultiQueries=true&useSSL=true
    password: enteradmin
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true
  thymeleaf:
    cache: false
    cache-period: 0
    content-type: text/html
    mode: LEGACYHTML5
    prefix: classpath:/templates
  template:
              cache: false
  mail:
    host: smtp.qq.com
    username: entermedia1024@qq.com
    password: ihdubvihqpmwcgjd
    port: 587
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
