spring:
  database:
    driverClassName: com.mysql.jdbc.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      charset: utf-8
      force: true
#mybatis分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params:
#    count: countSql
mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.audio.electric.domain
