// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package general;

public interface App extends Ice.Object,
                             _AppOperations, _AppOperationsNC
{
    public static final String ice_staticId = "::Demo::App";

    public static final long serialVersionUID = -81913185L;
}
