// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package general;

public interface AppPrx extends Ice.ObjectPrx
{
    public void receive(Message msg);

    public void receive(Message msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_receive(Message msg);

    public Ice.AsyncResult begin_receive(Message msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_receive(Message msg, Ice.Callback __cb);

    public Ice.AsyncResult begin_receive(Message msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_receive(Message msg, Callback_App_receive __cb);

    public Ice.AsyncResult begin_receive(Message msg, java.util.Map<String, String> __ctx, Callback_App_receive __cb);

    public Ice.AsyncResult begin_receive(Message msg,
                                         IceInternal.Functional_VoidCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_receive(Message msg,
                                         IceInternal.Functional_VoidCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_receive(Message msg,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_VoidCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_receive(Message msg,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_VoidCallback __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_receive(Ice.AsyncResult __result);

    public void receiveList(Message[] msgs);

    public void receiveList(Message[] msgs, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_receiveList(Message[] msgs);

    public Ice.AsyncResult begin_receiveList(Message[] msgs, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_receiveList(Message[] msgs, Ice.Callback __cb);

    public Ice.AsyncResult begin_receiveList(Message[] msgs, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_receiveList(Message[] msgs, Callback_App_receiveList __cb);

    public Ice.AsyncResult begin_receiveList(Message[] msgs, java.util.Map<String, String> __ctx, Callback_App_receiveList __cb);

    public Ice.AsyncResult begin_receiveList(Message[] msgs,
                                             IceInternal.Functional_VoidCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_receiveList(Message[] msgs,
                                             IceInternal.Functional_VoidCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_receiveList(Message[] msgs,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_VoidCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_receiveList(Message[] msgs,
                                             java.util.Map<String, String> __ctx,
                                             IceInternal.Functional_VoidCallback __responseCb,
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                             IceInternal.Functional_BoolCallback __sentCb);

    public void end_receiveList(Ice.AsyncResult __result);
}
