// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Callback.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package general;

public interface _TomOperations
{
    void addClient(Ice.Identity ident, String userId, Ice.Current __current);

    void addMsg(Ice.Identity ident, Message msg, Ice.Current __current);

    void logoutClient(Ice.Identity ident, String userId, Ice.Current __current);
}
